language: r
os: linux
dist: bionic
  
r:
  - 3.3
  - 3.4
  - 3.5
  - oldrel
  - release
  - devel

script:
  - R CMD build .
  - R CMD check mlm_*tar.gz
  - R CMD INSTALL mlm_*tar.gz
  - bash ci/run.sh 
  
