language: r
os: linux
dist: bionic
  
r:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - oldrel
  - release
  - devel

script:
  - R CMD build .
  - R CMD check *tar.gz
  - bash ci/run.sh 
