# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DoubleCentre <- function(A) {
    .Call('_mlm_DoubleCentre', PACKAGE = 'mlm', A)
}

timesTwo <- function(x) {
    .Call('_mlm_timesTwo', PACKAGE = 'mlm', x)
}

